[package]
name = "rust_fuse"
version = "0.1.0"
authors = ["y-okubo"]
edition = "2018"

[dependencies]
fuse = "0.3"
log = "0.4.0"
env_logger = "0.6.1"
libc = "0.2.58"
time = "0.1"
nix = "0.14.1"
ctrlc = "3.1.3"
